package features

import (
	"fmt"
	"maps"
	"slices"
	"testing"
	"time"

	"github.com/mft/core/contracts"
)

// mixedBar is one literal bar of the golden fixture. The minute is an offset
// from 13:20 IST on 2026-08-03, which is 07:50 UTC: the IST hour rolls over at
// bar 40 and the UTC hour at bar 10, so a builder that confused the two zones
// would fail the golden rather than pass it quietly.
type mixedBar struct {
	minute                 int
	open, high, low, close float64
	volume                 int64
}

// mixedFixtureStart is 2026-08-03 07:50 UTC, which is 13:20 IST.
var mixedFixtureStart = time.Date(2026, 8, 3, 7, 50, 0, 0, time.UTC)

// Generated by .tmp-ref/mixed_fixture.py. Every bar is a literal, and
// the minute is an offset from 13:20 IST on 2026-08-03.
var mixedBars = []mixedBar{
	{0, 2928.50, 2930.35, 2928.20, 2930.00, 1000},
	{1, 2930.00, 2932.90, 2929.66, 2932.50, 1250},
	{2, 2932.50, 2932.95, 2929.37, 2929.75, 1500},
	{3, 2929.75, 2930.25, 2924.70, 2925.00, 1750},
	{4, 2925.00, 2928.60, 2924.66, 2928.25, 2000},
	{5, 2928.25, 2933.40, 2927.87, 2933.00, 2250},
	{6, 2933.00, 2933.45, 2930.80, 2931.10, 2500},
	{7, 2931.10, 2931.60, 2927.46, 2927.80, 2750},
	{8, 2927.80, 2928.15, 2922.02, 2922.40, 3000},
	{9, 2922.40, 2925.35, 2922.10, 2924.95, 1000},
	{10, 2924.95, 2931.05, 2924.61, 2930.60, 1250},
	{11, 2930.60, 2936.90, 2930.22, 2936.40, 1500},
	{12, 2936.40, 2936.75, 2933.95, 2934.25, 1750},
	{13, 2934.25, 2934.65, 2928.56, 2928.90, 2000},
	{14, 2928.90, 2929.35, 2925.97, 2926.35, 2250},
	{15, 2926.35, 2930.20, 2926.05, 2929.70, 2500},
	{16, 2929.70, 2933.50, 2929.36, 2933.15, 2750},
	{17, 2933.15, 2933.55, 2930.62, 2931.00, 3000},
	{18, 2931.00, 2931.45, 2926.50, 2926.80, 1000},
	{19, 2926.80, 2927.30, 2926.01, 2926.35, 1250},
	{20, 2926.35, 2926.70, 2925.97, 2926.35, 1500},
	{21, 2926.35, 2926.75, 2926.05, 2926.35, 1750},
	{22, 2926.35, 2926.80, 2926.01, 2926.35, 2000},
	{23, 2926.35, 2926.85, 2925.97, 2926.35, 2250},
	{24, 2926.35, 2926.70, 2926.05, 2926.35, 2500},
	{25, 2926.35, 2926.35, 2926.35, 2926.35, 2750},
	{26, 2926.35, 2926.80, 2925.97, 2926.35, 3000},
	{27, 2926.35, 2926.85, 2926.05, 2926.35, 1000},
	{28, 2926.35, 2926.70, 2926.01, 2926.35, 1250},
	{29, 2926.35, 2926.75, 2925.97, 2926.35, 1500},
	{30, 2926.35, 2926.80, 2926.05, 2926.35, 1750},
	{31, 2926.35, 2926.85, 2926.01, 2926.35, 2000},
	{32, 2926.35, 2926.70, 2925.97, 2926.35, 2250},
	{33, 2926.35, 2926.75, 2926.05, 2926.35, 0},
	{34, 2926.35, 2926.80, 2926.01, 2926.35, 2750},
	{35, 2926.35, 2926.85, 2925.97, 2926.35, 3000},
	{36, 2926.35, 2926.70, 2926.05, 2926.35, 1000},
	{37, 2926.35, 2926.75, 2926.01, 2926.35, 1250},
	{38, 2926.35, 2926.80, 2925.97, 2926.35, 1500},
	{39, 2926.35, 2926.85, 2926.05, 2926.35, 1750},
	{40, 2926.35, 2926.70, 2926.01, 2926.35, 2000},
	{41, 2926.35, 2926.75, 2925.97, 2926.35, 2250},
	{42, 2926.35, 2926.80, 2926.05, 2926.35, 2500},
	{43, 2926.35, 2926.85, 2926.01, 2926.35, 2750},
	{44, 2926.35, 2928.25, 2925.97, 2927.90, 3000},
	{45, 2927.90, 2931.65, 2927.60, 2931.25, 1000},
	{46, 2931.25, 2936.05, 2930.91, 2935.60, 1250},
	{47, 2935.60, 2936.10, 2933.02, 2933.40, 1500},
	{48, 2933.40, 2933.75, 2929.55, 2929.85, 1750},
	{49, 2929.85, 2930.25, 2926.76, 2927.10, 2000},
	{50, 2927.10, 2927.55, 2923.37, 2923.75, 2250},
	{51, 2923.75, 2925.80, 2923.45, 2925.30, 2500},
	{52, 2925.30, 2930.30, 2924.96, 2929.95, 2750},
	{53, 2929.95, 2934.80, 2929.57, 2934.40, 3000},
	{54, 2934.40, 2938.60, 2934.10, 2938.15, 1000},
	{55, 2938.15, 2938.65, 2935.36, 2935.70, 1250},
	{56, 2935.70, 2936.05, 2930.87, 2931.25, 1500},
	{57, 2931.25, 2931.65, 2928.30, 2928.60, 1750},
	{58, 2928.60, 2930.60, 2928.26, 2930.15, 2000},
	{59, 2930.15, 2935.20, 2929.77, 2934.70, 2250},
	{60, 2934.70, 2938.25, 2934.40, 2937.90, 2500},
	{61, 2937.90, 2938.30, 2934.91, 2935.25, 2750},
	{62, 2935.25, 2935.70, 2931.22, 2931.60, 3000},
	{63, 2931.60, 2932.10, 2928.75, 2929.05, 1000},
}

// mixedCandles materialises the fixture as a candle window.
func mixedCandles() []contracts.Candle {
	out := make([]contracts.Candle, len(mixedBars))
	for i, b := range mixedBars {
		out[i] = contracts.Candle{
			Symbol:    "RELIANCE",
			Timestamp: mixedFixtureStart.Add(time.Duration(b.minute) * time.Minute),
			Open:      b.open,
			High:      b.high,
			Low:       b.low,
			Close:     b.close,
			Volume:    b.volume,
		}
	}
	return out
}

// mixedGolden holds the feature row expected at seven indices of mixedCandles,
// one row per named feature, in DefaultColumns order.
//
// The values were produced by a second, independent implementation of
// docs/contracts.md section 4 written from that table rather than from this
// package, so they check the code against the contract instead of checking the
// code against itself. The interesting rows are:
//
//	25  a doji: high == low == close, so there is no range to measure
//	33  a bar that never traded
//	39  the end of the 25-bar flat stretch: 20 flat closes, so vol_20 is 0
//	59  the last warm-up row: everything but ret_60 is defined
//	60  the first predictable row: ret_60 becomes non-zero exactly here
//	61, 63  ordinary trading, to catch a window that is off by one or two
var mixedGolden = map[int][18]float64{
	25: {
		0.0,                     // ret_1
		0.0,                     // ret_5
		-0.0014512675525445626,  // ret_15
		0.0,                     // ret_60
		0.0,                     // vol_5
		0.0011043143462060633,   // vol_20
		0.0,                     // vol_ratio
		0.0,                     // range_1
		0.0,                     // body_1
		0.0,                     // upper_wick_1
		0.0,                     // lower_wick_1
		1.0443214115521073,      // volume_z_20
		1.3333333333333333,      // volume_ratio
		-0.42494714587737636,    // momentum_rsi_14
		-0.00040648462531683757, // sma_gap_10
		270,                     // minute_of_session
		13.0,                    // hour_of_day
		0.0,                     // spread_proxy
	},
	33: {
		0.0,                     // ret_1
		0.0,                     // ret_5
		-0.00015376335849483406, // ret_15
		0.0,                     // ret_60
		0.0,                     // vol_5
		0.0005634701155486344,   // vol_20
		0.0,                     // vol_ratio
		0.00023920583662250682,  // range_1
		0.0,                     // body_1
		0.5714285714284786,      // upper_wick_1
		0.42857142857152136,     // lower_wick_1
		-2.4680122840753356,     // volume_z_20
		0.0,                     // volume_ratio
		0.0,                     // momentum_rsi_14
		0.0,                     // sma_gap_10
		278,                     // minute_of_session
		13.0,                    // hour_of_day
		0.0,                     // spread_proxy
	},
	39: {
		0.0,                    // ret_1
		0.0,                    // ret_5
		0.0,                    // ret_15
		0.0,                    // ret_60
		0.0,                    // vol_5
		0.0,                    // vol_20
		0.0,                    // vol_ratio
		0.00027337809899710626, // range_1
		0.0,                    // body_1
		0.6249999999998579,     // upper_wick_1
		0.3750000000001421,     // lower_wick_1
		-0.114818266017527,     // volume_z_20
		0.9523809523809523,     // volume_ratio
		0.0,                    // momentum_rsi_14
		0.0,                    // sma_gap_10
		284,                    // minute_of_session
		13.0,                   // hour_of_day
		0.0,                    // spread_proxy
	},
	59: {
		0.0015516171471903768,  // ret_1
		-0.0011748981829473085, // ret_5
		0.002319790894646249,   // ret_15
		0.0,                    // ret_60
		0.001247654089422805,   // vol_5
		0.0010473844585953587,  // vol_20
		1.1912092824978775,     // vol_ratio
		0.0018502743040173907,  // range_1
		0.0015528215279080344,  // body_1
		0.09208103130755342,    // upper_wick_1
		0.0699815837937607,     // lower_wick_1
		0.3765281664198343,     // volume_z_20
		1.1180124223602483,     // volume_ratio
		0.07459459459459072,    // momentum_rsi_14
		0.0011957580440740566,  // sma_gap_10
		304,                    // minute_of_session
		14.0,                   // hour_of_day
		0.002022222222222101,   // spread_proxy
	},
	60: {
		0.0010898070077018326, // ret_1
		0.0007491147176797805, // ret_5
		0.002266087200268932,  // ret_15
		0.0026926173837455623, // ret_60
		0.0013116959752232998, // vol_5
		0.001067733562662053,  // vol_20
		1.2284862264261922,    // vol_ratio
		0.0013104598522755587, // range_1
		0.0010904010631411297, // body_1
		0.0909090909090587,    // upper_wick_1
		0.0779220779221178,    // lower_wick_1
		0.7225645704089545,    // volume_z_20
		1.2269938650306749,    // volume_ratio
		0.050997782705103356,  // momentum_rsi_14
		0.0018038539048835062, // sma_gap_10
		305,                   // minute_of_session
		14.0,                  // hour_of_day
		0.0012800000000001092, // spread_proxy
	},
	61: {
		-0.0009024118845372993,  // ret_1
		0.0013636753157316955,   // ret_5
		-0.00011923316058651956, // ret_15
		0.0009373269826907638,   // ret_60
		0.0011330974716226728,   // vol_5
		0.0010952083597436232,   // vol_20
		1.0345953457549566,      // vol_ratio
		0.001154927178264314,    // range_1
		-0.0009020048333844211,  // body_1
		0.11799410029500068,     // upper_wick_1
		0.1002949852507707,      // lower_wick_1
		1.0443214115521073,      // volume_z_20
		1.3333333333333333,      // volume_ratio
		0.04061470911086462,     // momentum_rsi_14
		0.0005607435220488041,   // sma_gap_10
		306,                     // minute_of_session
		14.0,                    // hour_of_day
		0.0009636363636363967,   // spread_proxy
	},
	63: {
		-0.0008702106970792491,  // ret_1
		-0.00037547788535073943, // ret_5
		-0.0002730888067629261,  // ret_15
		0.0013836576886589915,   // ret_60
		0.001292946595459203,    // vol_5
		0.0011588152037017476,   // vol_20
		1.1157487331275795,      // vol_ratio
		0.0011437155391679586,   // range_1
		-0.0008698321735570089,  // body_1
		0.14925373134328762,     // upper_wick_1
		0.08955223880602688,     // lower_wick_1
		-1.414213562373095,      // volume_z_20
		0.5,                     // volume_ratio
		0.04290429042904864,     // momentum_rsi_14
		-0.0014267523740850942,  // sma_gap_10
		308,                     // minute_of_session
		14.0,                    // hour_of_day
		0.002549999999999727,    // spread_proxy
	},
}

// TestMixedSeriesMatchesGolden is the literal golden: a fixed, irregular price
// path with hand-checkable bars, compared value by value against features
// derived independently from the contract.
func TestMixedSeriesMatchesGolden(t *testing.T) {
	b := NewBuilder(tradingZone(t))
	table, err := b.Build(mixedCandles())
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	for _, i := range slices.Sorted(maps.Keys(mixedGolden)) {
		want := mixedGolden[i]
		if len(table.Columns) != len(want) {
			t.Fatalf("golden row has %d values but the table has %d columns", len(want), len(table.Columns))
		}
		for j, w := range want {
			assertClose(t, table.Rows[i][j], w, fmt.Sprintf("row %d %s", i, table.Columns[j]))
		}
	}
}

// TestMixedFixtureDegenerateRows spells out what three of the golden rows are
// for. The golden pins their values; this pins their meaning, so a future
// change to the policy cannot quietly redefine them.
func TestMixedFixtureDegenerateRows(t *testing.T) {
	b := NewBuilder(tradingZone(t))
	table, err := b.Build(mixedCandles())
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	const (
		doji        = 25 // high == low == close
		noVolume    = 33 // volume 0
		flatReturns = 39 // 20 flat closes behind it
	)

	t.Run("a doji has no range to measure", func(t *testing.T) {
		for _, name := range []string{"range_1", "body_1", "upper_wick_1", "lower_wick_1", "spread_proxy"} {
			if got := col(t, table, doji, name); got != 0 {
				t.Errorf("%s = %v on a doji, want 0", name, got)
			}
		}
	})

	t.Run("a bar that never traded", func(t *testing.T) {
		for _, name := range []string{"spread_proxy", "volume_ratio"} {
			if got := col(t, table, noVolume, name); got != 0 {
				t.Errorf("%s = %v on a zero-volume bar, want 0", name, got)
			}
		}
		// The zero volume still moves the z-score: it is far below the window
		// it is measured against.
		if got := col(t, table, noVolume, "volume_z_20"); got >= 0 {
			t.Errorf("volume_z_20 = %v on a zero-volume bar, want a negative z-score", got)
		}
	})

	t.Run("a window with no dispersion", func(t *testing.T) {
		for _, name := range []string{"vol_5", "vol_20", "vol_ratio", "momentum_rsi_14"} {
			if got := col(t, table, flatReturns, name); got != 0 {
				t.Errorf("%s = %v on a 20-bar flat window, want 0", name, got)
			}
		}
		// sma_gap_10 is zero too, but only to within the rounding of summing
		// ten copies of the same price and dividing by ten.
		assertClose(t, col(t, table, flatReturns, "sma_gap_10"), 0, "sma_gap_10 on a flat window")
	})

	t.Run("the warm-up boundary", func(t *testing.T) {
		if got := col(t, table, WarmupRows-1, "ret_60"); got != 0 {
			t.Errorf("ret_60 = %v on row %d, want 0: no row before the warm-up is a target", got, WarmupRows-1)
		}
		if !IsWarmup(WarmupRows - 1) {
			t.Error("row WarmupRows-1 must be a warm-up row")
		}
		if IsWarmup(WarmupRows) {
			t.Error("row WarmupRows must be a prediction target")
		}
	})
}
